-- Enable Row Level Security (RLS) for all tables
-- This ensures that users can ONLY access their own data.

-- 1. Profiles Table (Extends Supabase Auth)
-- Automatically created via triggers when a user signs up.
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  website TEXT,
  safe_word TEXT DEFAULT 'Blueberry Pancakes', -- For triggering Secure View
  duress_word TEXT DEFAULT 'Burnt Toast' -- For triggering Duress View
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own profile." 
  ON public.profiles FOR SELECT 
  USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile." 
  ON public.profiles FOR UPDATE 
  USING (auth.uid() = id);

-- 2. Incidents Table (Core Logging)
-- Stores the secure logs, AI analysis, and metadata.
CREATE TABLE public.incidents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Core Data
  date_of_incident TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT,
  category TEXT NOT NULL, -- e.g. "Coercive Control", "Physical Abuse"
  
  -- Descriptions
  raw_text TEXT NOT NULL, -- The user's original words
  ai_summary TEXT, -- The legal translation generated by AI
  
  -- Validation & Tags
  validation_message TEXT, -- AI's validating response
  tags TEXT[], -- Array of strings e.g. ["Isolation", "Financial Control"]
  
  -- UI Metadata
  color_code TEXT, -- e.g. "bg-red-50"
  marker_class TEXT -- e.g. "bg-red-600"
);

ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own incidents." 
  ON public.incidents FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own incidents." 
  ON public.incidents FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own incidents." 
  ON public.incidents FOR UPDATE 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own incidents." 
  ON public.incidents FOR DELETE 
  USING (auth.uid() = user_id);

-- 3. Evidence Table (Digital Locker)
-- Stores metadata for uploaded files with SHA-256 hashes for integrity.
CREATE TABLE public.evidence (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- File Metadata
  file_name TEXT NOT NULL,
  file_type TEXT NOT NULL, -- e.g. "image/jpeg", "audio/mp3"
  file_size TEXT NOT NULL, -- e.g. "2.4MB"
  file_hash TEXT NOT NULL, -- SHA-256 Hash for "Digital Fingerprint" chain of custody
  
  -- Storage
  storage_path TEXT NOT NULL, -- Path in Supabase Storage bucket
  
  -- Associations
  incident_id UUID REFERENCES public.incidents(id) ON DELETE SET NULL -- Optional link to specific log
);

ALTER TABLE public.evidence ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own evidence." 
  ON public.evidence FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own evidence." 
  ON public.evidence FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own evidence." 
  ON public.evidence FOR DELETE 
  USING (auth.uid() = user_id);

-- 4. Handover & Child Welfare Logs
-- Specific logs for child handovers and welfare concern tracking.
CREATE TABLE public.handovers (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Context
  handover_date TIMESTAMP WITH TIME ZONE NOT NULL,
  timeliness TEXT, -- "On Time", "Late (15m+)", etc.
  location TEXT,
  
  -- Participants & State
  parent_state TEXT[], -- ["Hostile", "Aggressive", "Under Influence"]
  third_party_present TEXT, -- Name of any new partner/relative present
  
  -- Child's Condition
  pre_contact_mood TEXT[], -- ["Crying", "Clinging"]
  post_contact_mood TEXT[], -- ["Hungry", "Dirty", "Upset"]
  child_voice_quote TEXT, -- Direct quotes from the child
  recovery_time TEXT, -- "2 hours", "Overnight"
  
  -- Checklist
  items_returned BOOLEAN DEFAULT TRUE,
  clothing_appropriate BOOLEAN DEFAULT TRUE,
  
  -- Notes
  notes TEXT,
  legal_tags TEXT[] -- ["Alienation Risk", "Neglect Concern"]
);

ALTER TABLE public.handovers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own handovers." 
  ON public.handovers FOR SELECT 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own handovers." 
  ON public.handovers FOR INSERT 
  WITH CHECK (auth.uid() = user_id);

-- 5. Safety Plan Contacts
CREATE TABLE public.safety_contacts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  name TEXT NOT NULL,
  role TEXT NOT NULL, -- "Lawyer", "Safe Contact", "School"
  contact_info TEXT, -- Phone or Email
  is_emergency BOOLEAN DEFAULT FALSE
);

ALTER TABLE public.safety_contacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own safety contacts." 
  ON public.safety_contacts FOR ALL 
  USING (auth.uid() = user_id);

-- 6. Duress Log (Gratitude Journal)
-- The "Fake" data shown to abusers.
CREATE TABLE public.duress_entries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  title TEXT NOT NULL,
  entry_text TEXT NOT NULL,
  entry_date TIMESTAMP WITH TIME ZONE NOT NULL
);

ALTER TABLE public.duress_entries ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their duress entries." 
  ON public.duress_entries FOR ALL 
  USING (auth.uid() = user_id);

-- Trigger to create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
